---
- hosts: localhost
  tasks:
     - name: get git_key
       command: cat ../token
       register: git_key
     - name: Create a github Repository
       github_repo:
        github_auth_key: "{{ git_key.stdout }}"
        name: "sigi-repo"
        description: "Ansible module for github"
        private: no
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
       register: result